# Change these to your GitHub username and repo name
owner: canadaxfx
repo: web-status

# Your monitored sites
sites:
  - name: XZ Studio Gallery
    url: https://xz-studio-gallery.com/
    icon: https://www.google.com/s2/favicons?sz=64&domain=github.com
  - name: XZ HD Gallery Misc
    url: https://canadaxfx.github.io/XZ-HD-Gallery-Misc/
    icon: https://www.google.com/s2/favicons?sz=64&domain=github.com
  - name: XZ Social Media Archive
    url: https://canadaxfx.github.io/XZ-social-media-archive/
    icon: https://www.google.com/s2/favicons?sz=64&domain=github.com
  - name: Screen Arts of Xiao Zhan
    url: https://canadaxfx.github.io/XZworks/
    icon: https://www.google.com/s2/favicons?sz=64&domain=github.com
  - name: XZ Screen Universe on YouTube
    url: https://canadaxfx.github.io/XZYT/
    icon: https://www.google.com/s2/favicons?sz=64&domain=github.com
  - name: Xiao Zhan Social Media Hub
    url: https://canadaxfx.github.io/xiaozhan/
    icon: https://www.google.com/s2/favicons?sz=64&domain=github.com
  - name: Claude-Powered Text Editor
    url: https://claude-text-editor.onrender.com/
    icon: https://www.google.com/s2/favicons?sz=64&domain=github.com
  - name: Email Reply App
    url: https://email-reply-app.onrender.com/
    icon: https://www.google.com/s2/favicons?sz=64&domain=github.com

# Status Website Settings
status-website:
  title: Web Status
  introTitle: "**Upptime** Status Page"
  introMessage: This page monitors the availability of Xiao Zhan fansites hosted on GitHub Pages and Render.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/canadaxfx/web-status

# Upptime will automatically create GitHub Issues when a site is down.
# Custom CI schedule
workflowSchedule:
  uptime: "*/10 * * * *"
  graphs: "0 0 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
